<?php

/**
 * IdeDeploy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    webideapp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class IdeDeploy extends BaseIdeDeploy
{
  function hasAccess($id,$user)
  {
            $q = Doctrine_Query::create()
                ->select('p.*, d.*, i.*')
                ->from('IdeDeploy d, d.IdeProject p')
                ->where('d.id = ?', $id)
            ->andWhere('p.ide_user_id = ?', $user);

        $data = $q->fetchArray();
        if (count($data) > 0)
    {
      return true;
    }else{
      return false;
    }
  }
}
