<?php

/**
 * IdeDeployTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IdeDeployTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return object IdeDeployTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('IdeDeploy');
  }

}