<?php

/**
 * IdeKeyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IdeKeyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IdeKeyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IdeKey');
    }
}