<?php

/**
 * IdeKey
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    webideapp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class IdeKey extends BaseIdeKey
{

  function newKey($data,$userid,$pubkey)
  {

    //regist to db
    $key = new IdeKey();
    $key->setName($data->getValue('name'));
    $key->setDescription($data->getValue('description'));
    $key->setPubkey($pubkey);
    $key->setIdeUserId($userid);



    $key->save();

    return $key;
  }
  
    function newDefaultKey($uname,$pubkey)
  {
      
    //find user

           $q = Doctrine_Query::create()
                    ->select('a.id')
                    ->from('SfGuardUser a')
                    ->where('a.username = ?', $uname);

    $account = $q->fetchArray();
     
    //regist to db
    $key = new IdeKey();
    $key->setName("Default");
    $key->setDescription("Auto added when making account.");
    $key->setPubkey($pubkey);
    $key->setIdeUserId($account[0]["id"]);



    $key->save();

    return $key;
  }
  
      function newMysqlDB($uname,$pw)
  {
    //find user

           $q = Doctrine_Query::create()
                    ->select('a.id')
                    ->from('SfGuardUser a')
                    ->where('a.username = ?', $uname);

    $account = $q->fetchArray();
    
        $q = Doctrine_Query::create()
                ->update('SfGuardUserProfile a');
        $q->set('a.mysqlpw', '?', $pw);
        $q->where('a.user_id=?', $account[0]["id"]);
        $q->execute();
  }
  
      function hasAccess($id,$user)
  {
        $q = Doctrine_Query::create()
                    ->select('a.id')
                    ->from('IdeKey a')
                    ->where('a.id = ?', $id)
                    ->andWhere('a.ide_user_id = ?', $user);

    $account = $q->fetchArray();
    if (count($account) > 0)
    {
      return true;
    }else{
      return false;
    }
  }

   function isNameExist($name,$user){
     $q = Doctrine_Query::create()
                    ->select('a.*')
                    ->from('IdeKey a')
                    ->where('a.name = ?', $name)
                    ->andWhere('a.ide_user_id = ?', $user);

      $account = $q->fetchArray();
    if (count($account) > 0)
    {
      return true;
    }else{

      return false;
    }
  }
}
