<?php

/**
 * IdeLanguageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IdeLanguageTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return object IdeLanguageTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('IdeLanguage');
  }

}