<?php

/**
 * IdeLanguage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    webideapp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class IdeLanguage extends BaseIdeLanguage
{
      public function getShortname($id)
  {
   
           $q = Doctrine_Query::create()
                    ->select('a.*')
                    ->from('IdeLanguage a')
                    ->where('a.id = ?', $id);

        $account = $q->fetchArray();
    
        if(0<count($account)){
          return $account[0]["shortname"];
        }else{
          return null;
        }
  }
}
