<?php

/**
 * IdeProjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IdeProjectTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return object IdeProjectTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('IdeProject');
  }

}