<?php

/**
 * IdeVcsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IdeVcsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IdeVcsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IdeVcs');
    }
}