default:
  has_layout:     true
  layout:         member_layout
indexSuccess:
  has_layout:     true
  layout:         editor_layout
  stylesheets:    [main.css,blueprint/screen.css,webIDE.css,jdMenu2/jdMenu.css,jdMenu/jdMenu.slate.css,jquery-ui-1.8.16.custom/development-bundle/themes/base/jquery.ui.all.css,demo.css,filetree/src/skin/ui.dynatree.css,filetree/src/skin-vista/ui.dynatree.css,jquery-ui-1.8.16.custom/css/ui-lightness/jquery-ui-1.8.16.custom.css,jquery-ui-1.8.16.custom/css/blitzer/jquery-ui-1.8.16.custom.css,fileuploader/qunit/qunit.css,default.css,neat.css,elegant.css,cobalt.css,night.css,eclipse.css,suggestion.css,codemirror.css,docs.css,autosuggest.css,cobalt.css,codemirror-ui.css,default.css,demo.css,demo00.css,docs.css,eclipse.css,elegant.css,main.css,neat.css,night.css,style.css,suggestion.css,jquery.contextMenu-1.01/jquery.contextMenu.css]
  javascripts:    [codemirror.js,keyword.js,overlay.js,ruby.js,runmode.js,socket.io.js,suggestion.js,fileuploader/qunit/qunit.js,fileuploader/client/fileuploader.js,jquery-ui-1.8.16.custom/js/jquery-1.7.1.js,jquery-ui-1.8.16.custom/js/jquery-1.6.2.min.js,jquery-ui-1.8.16.custom/js/jquery-ui-1.8.16.custom.min.js,filetree/src/jquery.dynatree.min.js,jdMenu/jquery.bgiframe.js,jdMenu/jquery.dimensions.js,jdMenu/jquery.jdMenu.js,jquery-ui-1.8.16.custom/development-bundle/ui/jquery.ui.core.js,jquery-ui-1.8.16.custom/development-bundle/ui/jquery.ui.widget.js,jquery-ui-1.8.16.custom/development-bundle/ui/jquery.ui.position.js,jquery-ui-1.8.16.custom/development-bundle/ui/jquery.ui.button.js,jquery-ui-1.8.16.custom/development-bundle/ui/jquery.ui.menu.js,jquery-ui-1.8.16.custom/development-bundle/ui/jquery.ui.menubar.js,jdMenu2/jquery.js,jquery.scrollabletab.js,jquery.contextMenu-1.01/jquery.contextMenu.js,jquery.cookie.js,jquery.easy-confirm-dialog.js]
openSuccess:
  haslayout:      true
  layout:         xml
openError:
  haslayout:      true
  layout:         xml
writeSuccess:
  haslayout:      true
  layout:         xml
writeError:
  haslayout:      true
  layout:         xml
removeSuccess:
  haslayout:      true
  layout:         xml
removeError:
  haslayout:      true
  layout:         xml
mkfileSuccess:
  haslayout:      true
  layout:         xml
mkfileError:
  haslayout:      true
  layout:         xml
mkdirSuccess:
  haslayout:      true
  layout:         xml
mkdirError:
  haslayout:      true
  layout:         xml
moveSuccess:
  haslayout:      true
  layout:         xml
moveError:
  haslayout:      true
  layout:         xml
addSuccess:
  haslayout:      true
  layout:         xml
addError:
  haslayout:      true
  layout:         xml
commitSuccess:
  haslayout:      true
  layout:         xml
commitError:
  haslayout:      true
  layout:         xml
pullSuccess:
  haslayout:      true
  layout:         xml
pullError:
  haslayout:      true
  layout:         xml
pushSuccess:
  haslayout:      true
  layout:         xml
pushError:
  haslayout:      true
  layout:         xml
easycommitSuccess:
  haslayout:      true
  layout:         xml
easycommitError:
  haslayout:      true
  layout:         xml
addmodSuccess:
  haslayout:      true
  layout:         xml
addmodError:
  haslayout:      true
  layout:         xml