<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('sf_guard_user_profile', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'unique' => '1',
              'length' => '8',
             ),
             'email_new' => 
             array(
              'type' => 'string',
              'unique' => '1',
              'length' => '255',
             ),
             'firstname' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'lastname' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'validate_at' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'validate' => 
             array(
              'type' => 'string',
              'length' => '33',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'indexes' => 
             array(
              'validate' => 
              array(
              'fields' => 
              array(
               0 => 'validate',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('sf_guard_user_profile');
    }
}